"""role table name change

Revision ID: a5a80149206b
Revises: 0b37b8c4da30
Create Date: 2025-04-11 13:15:25.376204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a80149206b'
down_revision: Union[str, None] = '0b37b8c4da30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'roles', ['name'])
    op.drop_column('roles', 'role_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('role_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###
